language: cpp
dist: trusty
sudo: required

addons:
  apt:
    sources:
    - sourceline: deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8
      key_url: https://storage.googleapis.com/bazel-apt/doc/apt-key.pub.gpg
    - sourceline: deb http://us.archive.ubuntu.com/ubuntu/ xenial main universe
    packages:
    - bazel
    - g++
    - libboost-program-options-dev
    - libcpprest-dev
    - libgflags-dev
    - libgflags2v5
    - libgoogle-glog-dev
    - libgoogle-glog0v5

script:
- bazel test --test_output=all tests
- bazel build example
